### ISSUE TITLE
[dhalion] null exception for previousCheckpoint

### ISSUE THREAD

**Issue by huijunw** [apache/incubator-heron#2927]
We saw the below exception in the HealthMgr log. The exception was from Dhalion library. The exception caused the HealthMgr process to quit.

```
[2018-06-20 20:44:11 +0000] [STDERR] stderr: Exception in thread "main"   
[2018-06-20 20:44:11 +0000] [STDERR] stderr: java.util.concurrent.ExecutionException: java.lang.NullPointerException  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at org.apache.heron.healthmgr.HealthManager.main(HealthManager.java:241)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: Caused by: java.lang.NullPointerException  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.time.Instant.compareTo(Instant.java:1255)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.time.Instant.isBefore(Instant.java:1285)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at com.microsoft.dhalion.policy.PoliciesExecutor.lambda$null$0(PoliciesExecutor.java:83)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at com.microsoft.dhalion.policy.PoliciesExecutor.lambda$start$2(PoliciesExecutor.java:84)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  
[2018-06-20 20:44:11 +0000] [STDERR] stderr: 	at java.lang.Thread.run(Thread.java:748)  
```

I doubt the Null was from https://github.com/Microsoft/Dhalion/blob/0.2.1/src/main/java/com/microsoft/dhalion/policy/PoliciesExecutor.java#L74?

Btw, we have several jobs and saw this issue in only one job.

**Comment by avflor** [comment]
Hi @huijunw. The healthmgr logs the checkpoint values each time the policy is executed (see https://github.com/Microsoft/Dhalion/blob/0.2.1/src/main/java/com/microsoft/dhalion/policy/PoliciesExecutor.java#L77) Can you please post the log lines for the last 5 policy executions?

**Comment by huijunw** [comment]
Hi @avflor 

The healthmgr failed and quited in the first round policy execution, then restarted. There were no last 5 policy execution.

The issue is `previousCheckpoint ` is not initialized (null) in the first round policy execution. https://github.com/Microsoft/Dhalion/blob/0.2.1/src/main/java/com/microsoft/dhalion/policy/PoliciesExecutor.java#L137


```
[2018-06-27 23:15:11 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Logging setup done.  
[2018-06-27 23:15:11 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Static Heron config loaded successfully   
[2018-06-27 23:15:11 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Initializing health manager  
[2018-06-27 23:15:13 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Starting Curator client connecting to: xxxxxxx_zk
[2018-06-27 23:15:13 +0000] [INFO] org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting  
[2018-06-27 23:15:13 +0000] [INFO] org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED  
[2018-06-27 23:15:13 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Directory tree initialized.  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Starting Curator client connecting to: xxxxxxx_zk 
[2018-06-27 23:15:14 +0000] [INFO] org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Directory tree initialized.  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.HealthPolicyConfig: Health Policy Configuration:{health.policy.class=org.apache.heron.healthmgr.policy.AutoRestartBackpressureContainerPolicy, health.policy.interval.ms=120000, BackPressureDetector.noiseFilterMillis=20}  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Initializing auto-restart-backpressure-container with class org.apache.heron.healthmgr.policy.AutoRestartBackpressureContainerPolicy  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.sensors.MetricsCacheMetricsProvider: Metrics will be provided by MetricsCache at http://yyyyyyyyyy/stats  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Starting Health Manager  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Starting Health Manager metric posting thread  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.common.network.HeronClient: Connecting to endpoint: /127.0.0.1:31671  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.HealthManagerMetrics: Connected to Metrics Manager. Ready to send register request  
[2018-06-27 23:15:14 +0000] [INFO] com.microsoft.dhalion.policy.PoliciesExecutor: Executing Policy: AutoRestartBackpressureContainerPolicy, checkpoint: 2018-06-27T23:15:14.462Z  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.common.TopologyProvider: Fetching topology from state manager: zzzzzzzzzz  
[2018-06-27 23:15:14 +0000] [INFO] org.apache.heron.healthmgr.HealthManagerMetrics: We registered ourselves to the Metrics Manager  
[2018-06-27 23:15:15 +0000] [INFO] org.apache.heron.common.network.SocketChannelHelper: Forcing to flush data to socket with best effort.  
[2018-06-27 23:15:15 +0000] [INFO] org.apache.heron.common.network.HeronClient: To stop the HeronClient.  
[2018-06-27 23:15:15 +0000] [INFO] org.apache.heron.healthmgr.HealthManagerMetrics: SimpleMetricsManagerClient exits  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: Exception in thread "main"   
[2018-06-27 23:15:15 +0000] [STDERR] stderr: java.util.concurrent.ExecutionException: java.lang.NullPointerException  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at org.apache.heron.healthmgr.HealthManager.main(HealthManager.java:241)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: Caused by: java.lang.NullPointerException  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.time.Instant.compareTo(Instant.java:1255)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.time.Instant.isBefore(Instant.java:1285)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at com.microsoft.dhalion.policy.PoliciesExecutor.lambda$null$0(PoliciesExecutor.java:83)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at com.microsoft.dhalion.policy.PoliciesExecutor.lambda$start$2(PoliciesExecutor.java:84)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  
[2018-06-27 23:15:15 +0000] [STDERR] stderr: 	at java.lang.Thread.run(Thread.java:748)  
[2018-06-27 23:15:26 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Logging setup done.  
[2018-06-27 23:15:26 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Static Heron config loaded successfully   
[2018-06-27 23:15:26 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Initializing health manager  
[2018-06-27 23:15:27 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Starting Curator client connecting to: xxxxxxx_zk
[2018-06-27 23:15:27 +0000] [INFO] org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting  
[2018-06-27 23:15:27 +0000] [INFO] org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED  
[2018-06-27 23:15:27 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Directory tree initialized.  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Starting Curator client connecting to: xxxxxxx_zk
[2018-06-27 23:15:28 +0000] [INFO] org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.heron.statemgr.zookeeper.curator.CuratorStateManager: Directory tree initialized.  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.heron.healthmgr.HealthPolicyConfig: Health Policy Configuration:{health.policy.class=org.apache.heron.healthmgr.policy.AutoRestartBackpressureContainerPolicy, health.policy.interval.ms=120000, BackPressureDetector.noiseFilterMillis=20}  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Initializing auto-restart-backpressure-container with class org.apache.heron.healthmgr.policy.AutoRestartBackpressureContainerPolicy  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.heron.healthmgr.sensors.MetricsCacheMetricsProvider: Metrics will be provided by MetricsCache at http://yyyyyyyyyy/stats  
[2018-06-27 23:15:28 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Starting Health Manager  
[2018-06-27 23:15:29 +0000] [INFO] org.apache.heron.healthmgr.HealthManager: Starting Health Manager metric posting thread  
[2018-06-27 23:15:29 +0000] [INFO] org.apache.heron.common.network.HeronClient: Connecting to endpoint: /127.0.0.1:31671  
[2018-06-27 23:15:29 +0000] [INFO] org.apache.heron.healthmgr.HealthManagerMetrics: Connected to Metrics Manager. Ready to send register request  
[2018-06-27 23:15:29 +0000] [INFO] com.microsoft.dhalion.policy.PoliciesExecutor: Executing Policy: AutoRestartBackpressureContainerPolicy, checkpoint: 2018-06-27T23:15:29.036Z  
[2018-06-27 23:15:29 +0000] [INFO] org.apache.heron.healthmgr.common.TopologyProvider: Fetching topology from state manager: zzzzzzzzzz  
[2018-06-27 23:15:29 +0000] [INFO] org.apache.heron.healthmgr.HealthManagerMetrics: We registered ourselves to the Metrics Manager  
[2018-06-27 23:15:30 +0000] [INFO] org.apache.heron.common.network.SocketChannelHelper: Forcing to flush data to socket with best effort.  
[2018-06-27 23:15:30 +0000] [INFO] org.apache.heron.common.network.HeronClient: To stop the HeronClient.  
[2018-06-27 23:15:30 +0000] [INFO] org.apache.heron.healthmgr.HealthManagerMetrics: SimpleMetricsManagerClient exits  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: Exception in thread "main"   
[2018-06-27 23:15:30 +0000] [STDERR] stderr: java.util.concurrent.ExecutionException: java.lang.NullPointerException  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at org.apache.heron.healthmgr.HealthManager.main(HealthManager.java:241)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: Caused by: java.lang.NullPointerException  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.time.Instant.compareTo(Instant.java:1255)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.time.Instant.isBefore(Instant.java:1285)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at com.microsoft.dhalion.policy.PoliciesExecutor.lambda$null$0(PoliciesExecutor.java:83)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at com.microsoft.dhalion.policy.PoliciesExecutor.lambda$start$2(PoliciesExecutor.java:84)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  
[2018-06-27 23:15:30 +0000] [STDERR] stderr: 	at java.lang.Thread.run(Thread.java:748)  

```

**Comment by avflor** [comment]
Hi @huijunw We are making some changes to the Dhalion APIs that should be able to fix this problem. We will release a new Dhalion version soon.

**Comment by huijunw** [comment]
@avflor thank you !

**Comment by huijunw** [comment]
@avflor Is there ETA for the new Dhalion version? cc @maosongfu @nwangtw @nlu90

**Comment by avflor** [comment]
Hi @huijunw . We have done most of the changes in the APIs but need to do some more testing. I should be able to give a concrete estimate next week. Does this work for you?

**Comment by huijunw** [comment]
Hi @avflor just check in, how is the progress, and what is the eta? Thank you.

**Comment by ashvina** [comment]
@huijunw I am looking at this issue now. Will try to publish new dhalion version today/tomorrow.

**Comment by huijunw** [comment]
@ashvina cool. Thank you !
