### ISSUE TITLE
Cannot update Heron topology using SchedulerStateManagerAdaptor

### ISSUE THREAD

**Issue by Yitian-Zhang** [apache/incubator-heron#2946]
Hi, everyone. I am trying to create a Custom scheduler based on the Default Aurora Scheduler. And now, I want to be able to implement a feature that can be rescheduled after creating a job using the default aurora scheduler. But I have encountered the following problem. 
After created job by Default AuroraScheduler, I attempted to use UpdateTopologyManager object to update topology with a new PackingPlan. However the Exception happened:
```
Exception in thread java.util.ConcurrentModificationException: The update lock can not be obtained for topology AuroraMonitorSentenceWordCountTopology. Another actor is performing an update on it. Failing this request, try again once current update is complete
    at com.twitter.heron.scheduler.UpdateTopologyManager.updateTopology(UpdateTopologyManager.java:117)
    at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog.triggerSchedule(AuroraHotEdgeSchedulerWithTxtLog.java:323)
    at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog.access$400(AuroraHotEdgeSchedulerWithTxtLog.java:55)
    at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog$2.run(AuroraHotEdgeSchedulerWithTxtLog.java:258)
    at java.lang.Thread.run(Thread.java:748)
```
The update codes as follows:
```
PackingPlans.PackingPlan currentPackingPlan = serializer.toProto(packingPlan);
PackingPlans.PackingPlan proposedPackingPlan = serializer.toProto(newPackingPlan);
try {
     updateTopologyManager.updateTopology(currentPackingPlan, proposedPackingPlan);
} catch (ExecutionException | InterruptedException e) {
     FileUtils.writeToFile(filename, "Update topology error!!!");
     e.printStackTrace();
}
```
And this update operation is my first update process after default created job by AuroraScheduler. Before this update operation, I didn't execute any update operation. So I don't know who is taking the lock and how to release the lock correctly? And when will the process that is occupying the lock be completed? How to fix this exception? Thanks for your help.

**Comment by kramasamy** [comment]
@maosongfu - might know this.
