### ISSUE TITLE
SchedulerStateManagerAdaptor failed to fetch data from Zookeeper path in Heron Cluster

### ISSUE THREAD

**Issue by Yitian-Zhang** [apache/incubator-heron#2952]
In Heron, I instantiated a SchedulerStateManagerAdaptor named adaptor using IStateManager and created a new Runtime config to saved this adaptor. Then, I created a ISchedulerClient object for invoking its schedulerClient.updateTopology function. Code as follows:
Code1: Initialized the `SchedulerStateManagerAdaptor `in construction function of one class.
```
String stateMgrClass = Context.stateManagerClass(this.config); // get state manager instance
IStateManager stateMgr = null;
try {
     stateMgr = ReflectionUtils.newInstance(stateMgrClass);
     FileUtils.writeToFile(filename, "Create IStateManager object success...");
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
     e.printStackTrace();
}
stateMgr.initialize(this.config);
stateManagerAdaptor = new SchedulerStateManagerAdaptor(stateMgr, 5000);
```
Code2: Created new `Config `object and get `ISchedulerClient `instance.
```
Config runtime = Config.newBuilder()
                .putAll(primaryRuntime)
                .put(Key.TOPOLOGY_NAME, Context.topologyName(config))
                .put(Key.SCHEDULER_STATE_MANAGER_ADAPTOR, stateManagerAdaptor)
                .build();
ISchedulerClient schedulerClient = new SchedulerClientFactory(config, runtime).getSchedulerClient();
```
Code3: Invoked the `updateTopology `function of the `schedulerClient`.
```
if (!schedulerClient.updateTopology(updateTopologyRequest)) {
     throw new TopologyRuntimeManagementException(String.format(
             "Failed to update " + topology.getName() +" with Scheduler, updateTopologyRequest=" + updateTopologyRequest));
}
```
However, when running this scheduler, this Exception happened:
![image 8](https://user-images.githubusercontent.com/13564504/42319327-2ed4ef82-8084-11e8-87e1-23a303eeaf9a.png)
I don't know what's wrong with it! But when I invoke the `adaptor.getPhysicalPlan` in the file that created adaptor object, it worked. What reason caused this problem? Thanks for your help.

**Comment by Yitian-Zhang** [comment]
Does anyone know how to solve this problem? Or what is the cause of the problem?

**Comment by Yitian-Zhang** [comment]
@nwangtw  Thanks for your commit. Let's me introduce my question in detail. First, I created a CustomScheduler that have been deployed on Heron. In the CustomScheduler, besides the main thread that heron runs, I created a new thread after created job by Heron. The new created Thread is responsible for running my programs. This problem is happening in the thread I created.
Second, I can submit topologies and activate them normally using the CustomScheduler.  So that means my CustomScheduler is deployed correctly and the main thread is right.
For your curious, my submit commands is:
`heron submit aurora/yitian/devel --config-path ~/.heron/conf ~/aurora-topolgoies/heron-with-dependencies.jar zyt.custom.topology.aurora.SentenceWordCountTopology SentenceWordCountTopology --deploy-deactivated --verbose`
As for this problem happened in the new thread that I created as above mentioned. In this new thread, I wanted to update a topology when it was running by using UpdateTopologyManager with a new PackingPlan. I want to make the effect of this method just like using the update command to update the topology. So I attempted to create ISchedulerClient and new runtime Config to update the topology by invoking ISchedulerClient.updateTopology function. Then this problem happened. 
I sorry for I couldn't give more information about the WARNING, because it is the only information I can find out. But here is my code:
```
public void doSchedule(PackingPlan packingPlan) {
        String stateMgrClass = Context.stateManagerClass(this.config); // get state manager instance
        IStateManager stateMgr = null;
        try {
            stateMgr = ReflectionUtils.newInstance(stateMgrClass);
            FileUtils.writeToFile(filename, "Create IStateManager object success...");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
            e.printStackTrace();
        }

        try {
            stateMgr.initialize(this.config);
            SchedulerStateManagerAdaptor stateManagerAdaptor = new SchedulerStateManagerAdaptor(stateMgr, 5000);
			
            // Then created the new packingplan. It is omitted here.
            PackingPlans.PackingPlan currentPackingPlan = serializer.toProto(packingPlan);
            PackingPlans.PackingPlan proposedPackingPlan = serializer.toProto(newPackingPlan);

            // build updatetopologyrequest object to update topogolgy
            Scheduler.UpdateTopologyRequest updateTopologyRequest =
                    Scheduler.UpdateTopologyRequest.newBuilder()
                            .setCurrentPackingPlan(currentPackingPlan)
                            .setProposedPackingPlan(proposedPackingPlan)
                            .build();

            // create runtime config using statemanageradaptor, this adaptor not included topology information
            // just add topologyname and adaptor to build schedulerCLient object
            Config primaryRuntime = LauncherUtils.getInstance().createPrimaryRuntime(topology);
            Config newRuntime = Config.newBuilder()
                    .putAll(primaryRuntime)
                    .put(Key.TOPOLOGY_NAME, Context.topologyName(config))
                    .put(Key.SCHEDULER_STATE_MANAGER_ADAPTOR, stateManagerAdaptor)
                    .build();
           
            // Create a ISchedulerClient basing on the config
            ISchedulerClient schedulerClient = getSchedulerClient(newRuntime);

			// In fact, I can't get the physicalplan right here by testing. I don't know why.
			// TopologyAPI.Topology topology3 = stateManagerAdaptor.getPhysicalPlan(topologyName).getTopology(); 

            if (!schedulerClient.updateTopology(updateTopologyRequest)) {
                throw new TopologyRuntimeManagementException(String.format(
                        "Failed to update " + topology.getName() + " with Scheduler, updateTopologyRequest="
                                + updateTopologyRequest));
            }
			
        } finally {
            // close zookeeper client connnection
            SysUtils.closeIgnoringExceptions(stateMgr);
        }
    }
```

**Comment by Yitian-Zhang** [comment]
I have updated the question in detail. Does anyone have any ideas?

**Comment by Yitian-Zhang** [comment]
@nwangtw Thanks a lot. Your understanding is corrent. I do want to get physical plan after the topology is submitted. I tried to get the physical plan after successfully submitting the topology for 3 minutes. At that time, the instances was running normally and registered in stmgrs(zookeeper). **But running updateTopology function still shows the same error as before.** I extracted the specific error message as shown below.
```
[2018-07-10 16:52:00 +0800] [WARNING] com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor: Exception processing future: java.lang.RuntimeException: Failed to fetch data from path: /heron/pplans/AuroraMonitorSentenceWordCountTopology  
[2018-07-10 16:52:00 +0800] [FINEST] org.apache.curator.utils.DefaultTracerDriver: Trace: DeleteBuilderImpl-Foreground - 7 ms  
[2018-07-10 16:52:00 +0800] [INFO] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager: Closing the CuratorClient to: heron01:2181  
[2018-07-10 16:52:00 +0800] [FINE] org.apache.curator.framework.imps.CuratorFrameworkImpl: Closing  
[2018-07-10 16:52:00 +0800] [FINE] org.apache.curator.CuratorZookeeperClient: Closing  
[2018-07-10 16:52:00 +0800] [FINE] org.apache.curator.ConnectionState: Closing  
[2018-07-10 16:52:00 +0800] [INFO] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager: Closing the tunnel processes  
Exception in thread "Thread-4" java.lang.NullPointerException
	at com.twitter.heron.scheduler.UpdateTopologyManager.getTopology(UpdateTopologyManager.java:338)
	at com.twitter.heron.scheduler.UpdateTopologyManager.updateTopology(UpdateTopologyManager.java:147)
	at com.twitter.heron.scheduler.UpdateTopologyManager.updateTopology(UpdateTopologyManager.java:112)
	at zyt.custom.my.scheduler.aurora.AuroraCustomScheduler.onUpdate(AuroraCustomScheduler.java:196)
	at com.twitter.heron.scheduler.client.LibrarySchedulerClient.updateTopology(LibrarySchedulerClient.java:70)
	at zyt.custom.my.scheduler.aurora.AuroraSchedulerController.triggerSchedule(AuroraSchedulerController.java:154)
	at zyt.custom.my.scheduler.aurora.AuroraSchedulerThread.run(AuroraSchedulerThread.java:45)
```
In Zookeeper, there will also be an Exception that the client disconnects after the connection is established. Is the failure to get physical plan because of  the disconnection of the zookeeper? What's more, Heron cluster uses zookeeper to run normally, but the client connection of this zookeeper failed. I cannot figure it out what's going on about it.
The EndOfStreamException of Zookeeper is as follows. And even if I use the default AuroraScheduler, Zookeeper still has the EndOfStreamException. Does this mean that there is a problem with zookeeper？ For more information on Zookeeper EndOfStreamException, there is the link: #2955 
```
2018-07-10 16:52:10,133 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164828618e9002c with negotiated timeout 30000 for client /218.195.228.28:44428
2018-07-10 16:52:10,137 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473bc zxid:0x1685 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:11,139 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473be zxid:0x1686 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:12,143 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473c0 zxid:0x1687 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:13,209 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473c2 zxid:0x1688 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:14,220 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473c4 zxid:0x1689 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:15,241 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473c6 zxid:0x168a txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:16,248 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473c8 zxid:0x168b txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:17,280 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473ca zxid:0x168c txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:18,304 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473cc zxid:0x168d txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:19,344 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473ce zxid:0x168e txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:20,347 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473d0 zxid:0x168f txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:21,353 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473d2 zxid:0x1690 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:22,361 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473d4 zxid:0x1691 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:23,368 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473d6 zxid:0x1692 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:24,372 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473d8 zxid:0x1693 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:25,001 [myid:] - INFO  [SessionTracker:ZooKeeperServer@358] - Expiring session 0x164828618e90022, timeout of 30000ms exceeded
2018-07-10 16:52:25,001 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x164828618e90022
2018-07-10 16:52:25,375 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473da zxid:0x1695 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:26,378 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473dc zxid:0x1696 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:27,379 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473de zxid:0x1697 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:28,386 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473e0 zxid:0x1698 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:29,393 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473e2 zxid:0x1699 txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:30,000 [myid:] - INFO  [SessionTracker:ZooKeeperServer@358] - Expiring session 0x164828618e90027, timeout of 30000ms exceeded
2018-07-10 16:52:30,001 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x164828618e90027
2018-07-10 16:52:30,395 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473e4 zxid:0x169b txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:31,401 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473e6 zxid:0x169c txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:32,409 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473e8 zxid:0x169d txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:33,413 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473ea zxid:0x169e txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:34,413 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x164828618e9002c type:create cxid:0x5b4473ec zxid:0x169f txntype:-1 reqpath:n/a Error Path:/heron/tmasters/AuroraMonitorSentenceWordCountTopology Error:KeeperErrorCode = NodeExists for /heron/tmasters/AuroraMonitorSentenceWordCountTopology
2018-07-10 16:52:35,001 [myid:] - INFO  [SessionTracker:ZooKeeperServer@358] - Expiring session 0x164828618e90025, timeout of 30000ms exceeded
2018-07-10 16:52:35,001 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x164828618e90025
2018-07-10 16:52:35,007 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x164828618e9002c, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)
2018-07-10 16:52:35,008 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /218.195.228.28:44428 which had sessionid 0x164828618e9002c
2018-07-10 16:52:45,072 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.28:44444
2018-07-10 16:52:45,074 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.28:44444; will be dropped if server is in r-o mode
2018-07-10 16:52:45,074 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.28:44444
2018-07-10 16:52:45,078 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164828618e9002d with negotiated timeout 30000 for client /218.195.228.28:44444
2018-07-10 16:53:05,000 [myid:] - INFO  [SessionTracker:ZooKeeperServer@358] - Expiring session 0x164828618e9002c, timeout of 30000ms exceeded
2018-07-10 16:53:05,000 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x164828618e9002c
```

**Comment by nwangtw** [comment]
Interesting. This looks tricky.

CLI does have the zk connection because state data on zk is needed to verify topology in submit and update commands. I am wondering if the UpdateTopologyManager is initialized correctly in your case, or maybe the the zk connection has been closed by the submission handler. Maybe worth checking with extra logs on the opening and closing of zk connection.

**Comment by Yitian-Zhang** [comment]
@nwangtw Thanks for your reply. In order to verify whether it is caused by the abnormality of zookeeper, I tested the same code in a single-node `local` environment with `the same zookeeper version`. The results show that in the local single-node environment, the physical plan data can be **successfully** obtained and the topology was updated successfully. But I don't know why it doesn't work in the Aurora+Mesos cluster environment.

What's more, by testing, I found that using the following code, the data can be successfully obtained in the single-node environment with zookeeper, but in the cluster environment, the `Could not getNodeData Exception` occurs.
The code: I can get the `ISchedulerStateManager `instance to obtain `physical plan` from zookeeper in single-node. But It does not work in Aurora cluster environment.
`stateManagerAdaptor = Runtime.schedulerStateManagerAdaptor(this.runtime);`
The Exception:
```
[2018-07-11 02:15:37 +0800] [WARNING] com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor: Exception processing future: java.lang.RuntimeException: Could not getNodeData  
Exception in thread "rescheduler" java.lang.NullPointerException
	at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog.getPhysicalPlanInfo(AuroraHotEdgeSchedulerWithTxtLog.java:384)
	at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog.triggerSchedule(AuroraHotEdgeSchedulerWithTxtLog.java:296)
	at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog.access$400(AuroraHotEdgeSchedulerWithTxtLog.java:65)
	at zyt.custom.my.scheduler.aurora.AuroraHotEdgeSchedulerWithTxtLog$2.run(AuroraHotEdgeSchedulerWithTxtLog.java:257)
	at java.lang.Thread.run(Thread.java:748)
```
So I confused that what is the difference between getting data from zookeeper in a single node or in the cluster environment?

**Comment by nwangtw** [comment]
Hmm. Not sure.

Maybe you could check in the aurora scheduler, the job has been started successfully and all the processes are running ok?

**Comment by Yitian-Zhang** [comment]
@nwangtw The Aurora scheduler shows that the job runs without problems, and the heron-ui also shows that the topology can run successfully.
![image 39](https://user-images.githubusercontent.com/13564504/42565038-eb40fc4c-8534-11e8-9cdf-a4d4e5f4174c.png)
![image 45](https://user-images.githubusercontent.com/13564504/42565054-f137ccca-8534-11e8-8ca7-7ddb1de40898.png)
In addition, as for the data in the zookeeper can be successfully obtained in the single-node environment, but failed in the cluster environment.  Is it possible that because the node running **tmaster** cannot get the data from the node running **zookeeper** (if they are running on different nodes) in a cluster environment? If it is, do you have any ideas about the cause of this problem? Thanks.

**Comment by Yitian-Zhang** [comment]
Do you have any suggestions on how to solve this problem? And I don't seem to be sure what the real cause of the problem is. @nwangtw Thanks so much.
