### ISSUE TITLE
Zookeeper EndOfStreamException happened when using AuroraScheduler

### ISSUE THREAD

**Issue by Yitian-Zhang** [apache/incubator-heron#2955]
There is a problem that bothers me. `EndOfStreamException `always happen in zookeeper after submitted topologies. Although it does not affect the normal operation of the cluster, I still hope to solve the problem because it may be affect other parts of Heron function.
The zookeeper version is `3.4.10` and was deployed on `standalone `mode in one host of my cluster. The contents of `zoo.cfg` are as follows. 
```
tickTime=10000
initLimit=100
syncLimit=50
dataDir=/home/yitian/zookeeper/data
dataLogDir=/home/yitian/zookeeper/logs
clientPort=2181
maxClientCnxns=100
server.1=heron01:2888:3888
```
Moreover, there is the `myid `file in `dataDir`, and its content is: `1`. That is my configuration of zookeeper.
The contents of the `statemgr.yaml` in heron are as follows:
```
com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager
heron.statemgr.connection.string:               "heron01:2181"
heron.statemgr.root.path:                       "/heron"
heron.statemgr.zookeeper.is.initialize.tree: True
```
There are four hosts in my Heron cluster, one mesos master host and three agent hosts. And in zookeeper log files, EndOfStreamException occurred in the three agent hosts. The contents of zookeeper.log are as follows:
```
2018-07-10 10:30:06,565 [myid:] - INFO  [main:QuorumPeerConfig@134] - Reading configuration from: /home/yitian/zookeeper/zookeeper-3.4.10/bin/../conf/zoo.cfg
2018-07-10 10:30:06,574 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: heron01 to address: heron01/218.195.228.24
2018-07-10 10:30:06,574 [myid:] - ERROR [main:QuorumPeerConfig@345] - Invalid configuration, only one server specified (ignoring)
2018-07-10 10:30:06,576 [myid:] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2018-07-10 10:30:06,576 [myid:] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2018-07-10 10:30:06,576 [myid:] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2018-07-10 10:30:06,576 [myid:] - WARN  [main:QuorumPeerMain@113] - Either no config or no quorum defined in config, running  in standalone mode
2018-07-10 10:30:06,584 [myid:] - INFO  [main:QuorumPeerConfig@134] - Reading configuration from: /home/yitian/zookeeper/zookeeper-3.4.10/bin/../conf/zoo.cfg
2018-07-10 10:30:06,584 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: heron01 to address: heron01/218.195.228.24
2018-07-10 10:30:06,584 [myid:] - ERROR [main:QuorumPeerConfig@345] - Invalid configuration, only one server specified (ignoring)
2018-07-10 10:30:06,585 [myid:] - INFO  [main:ZooKeeperServerMain@96] - Starting server
2018-07-10 10:30:06,589 [myid:] - INFO  [main:Environment@100] - Server environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
2018-07-10 10:30:06,589 [myid:] - INFO  [main:Environment@100] - Server environment:host.name=heron01
2018-07-10 10:30:06,589 [myid:] - INFO  [main:Environment@100] - Server environment:java.version=1.8.0_151
2018-07-10 10:30:06,589 [myid:] - INFO  [main:Environment@100] - Server environment:java.vendor=Oracle Corporation
2018-07-10 10:30:06,589 [myid:] - INFO  [main:Environment@100] - Server environment:java.home=/usr/java/jdk1.8.0_151/jre
2018-07-10 10:30:06,590 [myid:] - INFO  [main:Environment@100] - Server environment:java.class.path=/home/yitian/zookeeper/zookeeper-3.4.10/bin/../build/classes:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../build/lib/*.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/slf4j-log4j12-1.6.1.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/slf4j-api-1.6.1.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/netty-3.10.5.Final.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/log4j-1.2.16.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/jline-0.9.94.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../zookeeper-3.4.10.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../src/java/lib/*.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../conf:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../build/classes:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../build/lib/*.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/slf4j-log4j12-1.6.1.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/slf4j-api-1.6.1.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/netty-3.10.5.Final.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/log4j-1.2.16.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../lib/jline-0.9.94.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../zookeeper-3.4.10.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../src/java/lib/*.jar:/home/yitian/zookeeper/zookeeper-3.4.10/bin/../conf:.:/usr/java/jdk1.8.0_151/lib:/usr/java/jdk1.8.0_151/jre/lib
2018-07-10 10:30:06,590 [myid:] - INFO  [main:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2018-07-10 10:30:06,590 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=/tmp
2018-07-10 10:30:06,590 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
2018-07-10 10:30:06,590 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
2018-07-10 10:30:06,590 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
2018-07-10 10:30:06,591 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=4.13.0-43-generic
2018-07-10 10:30:06,591 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=yitian
2018-07-10 10:30:06,591 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/home/yitian
2018-07-10 10:30:06,591 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/home/yitian
2018-07-10 10:30:06,595 [myid:] - INFO  [main:ZooKeeperServer@829] - tickTime set to 5000
2018-07-10 10:30:06,595 [myid:] - INFO  [main:ZooKeeperServer@838] - minSessionTimeout set to -1
2018-07-10 10:30:06,595 [myid:] - INFO  [main:ZooKeeperServer@847] - maxSessionTimeout set to -1
2018-07-10 10:30:06,601 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2018-07-10 10:30:07,585 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39618
2018-07-10 10:30:07,600 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0004 at /218.195.228.24:39618
2018-07-10 10:30:07,608 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0004 with negotiated timeout 10000 for client /218.195.228.24:39618
2018-07-10 10:30:07,624 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@648] - Got user-level KeeperException when processing sessionid:0x16482052aec0004 type:create cxid:0x1c zxid:0x158f txntype:-1 reqpath:n/a Error Path:/aurora/scheduler/member_0000000454 Error:KeeperErrorCode = NodeExists for /aurora/scheduler/member_0000000454
2018-07-10 10:30:07,625 [myid:] - INFO  [SyncThread:0:FileTxnLog@203] - Creating new log file: log.158f
2018-07-10 10:30:09,917 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39622
2018-07-10 10:30:09,917 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39620
2018-07-10 10:30:09,917 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39622; will be dropped if server is in r-o mode
2018-07-10 10:30:09,917 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0000 at /218.195.228.24:39622
2018-07-10 10:30:09,918 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0000 with negotiated timeout 10000 for client /218.195.228.24:39622
2018-07-10 10:30:09,918 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39626
2018-07-10 10:30:09,918 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39620; will be dropped if server is in r-o mode
2018-07-10 10:30:09,919 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0006 at /218.195.228.24:39620
2018-07-10 10:30:09,919 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0006 with negotiated timeout 10000 for client /218.195.228.24:39620
2018-07-10 10:30:09,919 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39628
2018-07-10 10:30:09,919 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39626; will be dropped if server is in r-o mode
2018-07-10 10:30:09,919 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0001 at /218.195.228.24:39626
2018-07-10 10:30:09,920 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0001 with negotiated timeout 10000 for client /218.195.228.24:39626
2018-07-10 10:30:09,920 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39630
2018-07-10 10:30:09,920 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39628; will be dropped if server is in r-o mode
2018-07-10 10:30:09,920 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0007 at /218.195.228.24:39628
2018-07-10 10:30:09,921 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0007 with negotiated timeout 10000 for client /218.195.228.24:39628
2018-07-10 10:30:09,921 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39630; will be dropped if server is in r-o mode
2018-07-10 10:30:09,921 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0005 at /218.195.228.24:39630
2018-07-10 10:30:09,921 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0005 with negotiated timeout 10000 for client /218.195.228.24:39630
2018-07-10 10:30:09,922 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39632
2018-07-10 10:30:09,922 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39632; will be dropped if server is in r-o mode
2018-07-10 10:30:09,922 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0002 at /218.195.228.24:39632
2018-07-10 10:30:09,922 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0002 with negotiated timeout 10000 for client /218.195.228.24:39632
2018-07-10 10:30:09,922 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39634
2018-07-10 10:30:09,923 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.24:39634; will be dropped if server is in r-o mode
2018-07-10 10:30:09,923 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x16482052aec0003 at /218.195.228.24:39634
2018-07-10 10:30:09,925 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@687] - Established session 0x16482052aec0003 with negotiated timeout 10000 for client /218.195.228.24:39634
2018-07-10 10:56:28,040 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39852
2018-07-10 10:56:28,043 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.24:39852
2018-07-10 10:56:28,044 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770000 with negotiated timeout 30000 for client /218.195.228.24:39852
2018-07-10 10:56:37,924 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.24:39860
2018-07-10 10:56:37,925 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.24:39860
2018-07-10 10:56:37,926 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770001 with negotiated timeout 10000 for client /218.195.228.24:39860
2018-07-10 10:56:37,936 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x164820646770001
2018-07-10 10:56:37,941 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /218.195.228.24:39860 which had sessionid 0x164820646770001
2018-07-10 10:56:43,514 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.43:35560
2018-07-10 10:56:43,516 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.43:35560
2018-07-10 10:56:43,521 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770002 with negotiated timeout 10000 for client /218.195.228.43:35560
2018-07-10 10:56:44,022 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.19:50174
2018-07-10 10:56:44,026 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.19:50174
2018-07-10 10:56:44,031 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770003 with negotiated timeout 10000 for client /218.195.228.19:50174
2018-07-10 10:56:44,130 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.28:44134
2018-07-10 10:56:44,149 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.28:44134
2018-07-10 10:56:44,154 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770004 with negotiated timeout 10000 for client /218.195.228.28:44134
2018-07-10 10:56:45,730 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x164820646770000
2018-07-10 10:56:45,736 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /218.195.228.24:39852 which had sessionid 0x164820646770000
2018-07-10 10:57:16,966 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.43:35572
2018-07-10 10:57:16,970 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)
2018-07-10 10:57:16,977 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /218.195.228.43:35572 (no session established for client)
2018-07-10 10:57:16,979 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.43:35574
2018-07-10 10:57:16,980 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.43:35574
2018-07-10 10:57:16,984 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770005 with negotiated timeout 10000 for client /218.195.228.43:35574
2018-07-10 10:57:17,095 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.43:35578
2018-07-10 10:57:17,097 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.43:35578; will be dropped if server is in r-o mode
2018-07-10 10:57:17,097 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.43:35578
2018-07-10 10:57:17,101 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770006 with negotiated timeout 30000 for client /218.195.228.43:35578
2018-07-10 10:57:17,747 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.19:50186
2018-07-10 10:57:17,749 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)
2018-07-10 10:57:17,751 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /218.195.228.19:50186 (no session established for client)
2018-07-10 10:57:17,752 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.19:50188
2018-07-10 10:57:17,752 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.19:50188
2018-07-10 10:57:17,756 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770007 with negotiated timeout 10000 for client /218.195.228.19:50188
2018-07-10 10:57:18,742 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.19:50190
2018-07-10 10:57:18,743 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.19:50190; will be dropped if server is in r-o mode
2018-07-10 10:57:18,744 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.19:50190
2018-07-10 10:57:18,751 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770008 with negotiated timeout 30000 for client /218.195.228.19:50190
2018-07-10 10:57:20,456 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.43:35586
2018-07-10 10:57:20,458 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.43:35586
2018-07-10 10:57:20,463 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x164820646770009 with negotiated timeout 30000 for client /218.195.228.43:35586
2018-07-10 10:57:36,004 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.28:44146
2018-07-10 10:57:36,004 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)
2018-07-10 10:57:36,004 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /218.195.228.28:44146 (no session established for client)
2018-07-10 10:57:36,006 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.28:44148
2018-07-10 10:57:36,006 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.28:44148
2018-07-10 10:57:36,008 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x16482064677000a with negotiated timeout 10000 for client /218.195.228.28:44148
2018-07-10 10:57:36,892 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /218.195.228.28:44152
2018-07-10 10:57:36,893 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /218.195.228.28:44152; will be dropped if server is in r-o mode
2018-07-10 10:57:36,894 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /218.195.228.28:44152
2018-07-10 10:57:36,898 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x16482064677000b with negotiated timeout 30000 for client /218.195.228.28:44152
```
In above zookeeper.log, the host with IP:218.195.228.24 is the master node, hosts list with IP: 28, 19, 43 are agents nodes.
I have tried a lot of methods, but they don't work. What is the cause of the problem? And how can I fix it? Thanks a lot for your help.

**Comment by kramasamy** [comment]
I would look at the heron job submission path on the client side. It directly writes into zookeeper - which might not close the connection correctly. Does this occur in your custom scheduler or in Aurora scheduler?

**Comment by Yitian-Zhang** [comment]
@kramasamy Yes, this exception occurred both in my custom scheduler and  Aurora Scheduler.
