### ISSUE TITLE
The exception java.lang.VerifyError: Bad type on operand stack happend in CustomScheduler

### ISSUE THREAD

**Issue by Yitian-Zhang** [apache/incubator-heron#3033]
Hi, everyone. I tried to get the PhysicalPlan from zookeeper using the following codes:
```
String stateMgrClass = Context.stateManagerClass(this.config);
IStateManager stateManager = null;
stateManager = ReflectionUtils.newInstance(stateMgrClass);
stateManager.initialize(this.config);
SchedulerStateManagerAdaptor stateManagerAdaptor = new SchedulerStateManagerAdaptor(stateManager, 5000);
PhysicalPlans.PhysicalPlan physicalPlan = stateManagerAdaptor.getPhysicalPlan(this.topologyName);
```
And then the exceptiion: java.lang.VerifyError: Bad type on operand stack happened:
```
Exception in thread "Thread-4" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/twitter/heron/proto/system/PhysicalPlans$PhysicalPlan$Builder.getTopologyFieldBuilder()Lcom/google/protobuf/SingleFieldBuilderV3; @24: invokespecial
  Reason:
    Type 'com/twitter/heron/api/generated/TopologyAPI$Topology' (current frame, stack[3]) is not assignable to 'com/google/protobuf/AbstractMessage'
  Current Frame:
    bci: @24
    flags: { }
    locals: { 'com/twitter/heron/proto/system/PhysicalPlans$PhysicalPlan$Builder' }
    stack: { 'com/twitter/heron/proto/system/PhysicalPlans$PhysicalPlan$Builder', uninitialized 8, uninitialized 8, 'com/twitter/heron/api/generated/TopologyAPI$Topology', 'com/google/protobuf/GeneratedMessageV3$BuilderParent', integer }
  Bytecode:
    0x0000000: 2ab4 0014 c700 1f2a bb00 5d59 2ab6 0042
    0x0000010: 2ab6 005e 2ab6 005f b700 60b5 0014 2a01
    0x0000020: b500 092a b400 14b0                    
  Stackmap Table:
    same_frame(@35)

	at com.twitter.heron.proto.system.PhysicalPlans$PhysicalPlan.toBuilder(PhysicalPlans.java:4211)
	at com.twitter.heron.proto.system.PhysicalPlans$PhysicalPlan.newBuilder(PhysicalPlans.java:4204)
	at com.twitter.heron.statemgr.FileSystemStateManager.getPhysicalPlan(FileSystemStateManager.java:165)
	at com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor.getPhysicalPlan(SchedulerStateManagerAdaptor.java:289)
```
Any suggestions about how to solve this problem will helpful. Thanks.

**Comment by Yitian-Zhang** [comment]
This problem is caused by conflicts in some classes. And it has been solved by deleting the` heron-api:[HERON_VERSION].jar` from the `pom.xml`. But the `heron-spi:[HERON_VERSION].jar` is necessary to create a custom scheduler.
