### ISSUE TITLE
Bookkeeper IOException during upload

### ISSUE THREAD

**Issue by sautran** [apache/incubator-heron#3173]
deploy to minikube kubernetes cluster, Failed to upload, bookie has a lot error like the following:

2019-01-24 18:26:27,138 - ERROR - [BookieReadThread-3181-orderedsafeexecutor-0-0:ReadEntryProcessorV3@229] - IOException while reading entry: 3 from ledger 8 
java.io.IOException: problem found in 2@3 at position + 311544581 entry is 358 not 3
	at org.apache.bookkeeper.bookie.EntryLogger.readEntry(EntryLogger.java:879)
	at org.apache.bookkeeper.bookie.InterleavedLedgerStorage.getEntry(InterleavedLedgerStorage.java:319)
	at org.apache.bookkeeper.bookie.SortedLedgerStorage.getEntry(SortedLedgerStorage.java:133)
	at org.apache.bookkeeper.bookie.LedgerDescriptorImpl.readEntry(LedgerDescriptorImpl.java:150)
	at org.apache.bookkeeper.bookie.Bookie.readEntry(Bookie.java:1531)
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:172)
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:152)
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.getReadResponse(ReadEntryProcessorV3.java:215)
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.executeOp(ReadEntryProcessorV3.java:258)
	at org.apache.bookkeeper.proto.ReadEntryProcessorV3.safeRun(ReadEntryProcessorV3.java:254)
	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sautran** [comment]
Look like after I move to a powerful box. the issue is gones

**Comment by nwangtw** [comment]
a powerful box? interesting. Just to clarify. the box runs the topology and the bookkeeper is a remote service?

**Comment by sautran** [comment]
I have this powerful box having minikube hosting all the bookeeper, heron-api etc. services. I deploy the topology from my desktop to this box
