### ISSUE TITLE
DistributedLog based stateful storage backend is not working

### ISSUE THREAD

**Issue by simingweng** [apache/incubator-heron#3210]
when we switch to `org.apache.heron.statefulstorage.dlog.DlogStorage` as the stateful topology state storage backend, the checkpointing manager is always throwing exception when it tries to save state for any heron instance into Bookkeeper cluster via the DistributedLog API.

We're testing using Heron v0.20.1-incubating-rc1, deployed on Kubernetes cluster, with a StatefulSet of 3 Bookkeeper pods and a StatefulSet of 3 Zookeeper pods.

The exception we got in the checkpointing manager log is:

`
[2019-03-10 20:05:59 +0000] [WARNING] org.apache.heron.ckptmgr.CheckpointManagerServer: Save checkpoint not successful for checkpointId 1552074656671682557-1552248359 component sum-bolt instanceId 0 
org.apache.heron.spi.statefulstorage.StatefulStorageException: Failed to persist checkpoint @ /arithmetic-progression-sum/1552074656671682557-1552248359/sum-bolt_0
	at org.apache.heron.statefulstorage.dlog.DlogStorage.storeCheckpoint(DlogStorage.java:148)
	at org.apache.heron.ckptmgr.CheckpointManagerServer.handleSaveInstanceStateRequest(CheckpointManagerServer.java:248)
	at org.apache.heron.ckptmgr.CheckpointManagerServer.onRequest(CheckpointManagerServer.java:108)
	at org.apache.heron.common.network.HeronServer.handlePacket(HeronServer.java:212)
	at org.apache.heron.common.network.HeronServer.handleRead(HeronServer.java:169)
	at org.apache.heron.common.basics.NIOLooper.handleSelectedKeys(NIOLooper.java:116)
	at org.apache.heron.common.basics.NIOLooper.access$000(NIOLooper.java:38)
	at org.apache.heron.common.basics.NIOLooper$1.run(NIOLooper.java:51)
	at org.apache.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:191)
	at org.apache.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:110)
	at org.apache.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:100)
	at org.apache.heron.ckptmgr.CheckpointManager.startAndLoop(CheckpointManager.java:175)
	at org.apache.heron.ckptmgr.CheckpointManager.main(CheckpointManager.java:263)
Caused by: org.apache.distributedlog.exceptions.ZKException: Failed to create log /distributedlog/arithmetic-progression-sum/1552074656671682557-1552248359/sum-bolt_0/<default> : NONODE
	at org.apache.distributedlog.impl.metadata.ZKLogStreamMetadataStore$3.processResult(ZKLogStreamMetadataStore.java:471)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$3$1.processResult(ZooKeeperClient.java:472)
	at dlshade.org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:658)
	at dlshade.org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
`

The cause of the issue is that when `DlogStorage` tries to open a new stream for writing each checkpoint data, the stream name is built in such a pattern:

/{topology name}/{checkpoint id}/{component name}_{task id}

the slash in the stream name makes DistributedLog interpreter it as namespace path, and in `apachedistributedlog/distributedlog:0.5.0`, stream name does not support slash.

The latest release of DistributedLog `apache/bookkeeper:4.9.0` is confirmed to have supported handling stream name with slash in it. Here's how I tested with it:

`docker run -it --rm --entrypoint bash apache/bookkeeper:4.9.0 bin/dlog local 7000`

Then in another terminal:

`simingweng$ docker exec -it 83ccfcd92948 bin/dlog tool create -u distributedlog://127.0.0.1:7000/messaging/distributedlog -r sub/path -e 1` 83ccfcd92948 is my running container id.

`docker exec -it 83ccfcd92948 bin/dlog tool list -u distributedlog://127.0.0.1:7000/messaging/distributedlog`

Streams under distributedlog://127.0.0.1:7000/messaging/distributedlog : 

`sub`

`docker exec -it 83ccfcd92948 bin/dlog tool list -u distributedlog://127.0.0.1:7000/messaging/distributedlog/sub`

Streams under distributedlog://127.0.0.1:7000/messaging/distributedlog/sub : 

`path1`

**Comment by simingweng** [comment]
@sijie @nwangtw

**Comment by sijie** [comment]
I think dlog 0.5.0 doesn't support `/`. in order to support `/`, we have to bump the dlog version to the latest version.

**Comment by simingweng** [comment]
we need to upgrade from `apachedistributedlog:distributedlog:0.5.0` to `apache/bookkeeper:4.7.3`. The latest `apache/bookkeeper` image can not be used due to https://github.com/apache/bookkeeper/issues/1660

**Comment by nwangtw** [comment]
Is there any side effect with that change? All things should still work the same way?

If no concerns, let's do it~ Thanks!

**Comment by simingweng** [comment]
@nwangtw please assign this to me cuz' I've started working on it, actually, almost done the final testing. There will be some other minor implication to Heron after the upgrade, for example, the Kubernetes deployment manifest needs to be updated, because the startup mechanism is quite different now in `apache/bookkeeper`, the default dlog namespace is no longer created by default.

I added a `initContainer` to the heron deployment yaml, to manually create the namespace that Heron expects, also, the `distributedlog-core` maven dependencies needs to align with 4.7.3 as well.
