### ISSUE TITLE
Failed to submit topology to standalone cluster

### ISSUE THREAD

**Issue by Vxider** [apache/incubator-heron#3247]
Hi, I am setting up a four node standalone cluster following the [official document](https://apache.github.io/incubator-heron/docs/operators/deployment/schedulers/standalone/).

I got the successful startup message

```
heron-admin standalone cluster start                                    4.26 ⏱
[2019-04-26 17:31:53 +0000] [INFO]: Roles:
[2019-04-26 17:31:53 +0000] [INFO]:  - Master Servers: ['10Gdell125']
[2019-04-26 17:31:53 +0000] [INFO]:  - Slave Servers: ['10Gdell124', '10Gdell125', '10Gdell126', '10Gdell127']
[2019-04-26 17:31:53 +0000] [INFO]:  - Zookeeper Servers: ['10Gdell127:12181', '10Gdell126:12181', '10Gdell125:12181', '10Gdell124:12181']
[2019-04-26 17:31:53 +0000] [INFO]: Updating config files...
[2019-04-26 17:31:53 +0000] [INFO]: Distributing heron package to nodes (this might take a while)...
[2019-04-26 17:32:18 +0000] [INFO]: Server: 10Gdell124
[2019-04-26 17:32:18 +0000] [INFO]: Server: 10Gdell125
[2019-04-26 17:32:18 +0000] [INFO]: Server: 10Gdell126
[2019-04-26 17:32:18 +0000] [INFO]: Server: 10Gdell127
[2019-04-26 17:32:23 +0000] [INFO]: Done distributing packages
[2019-04-26 17:32:23 +0000] [INFO]: Starting master on 10Gdell125
[2019-04-26 17:32:24 +0000] [INFO]: Done starting masters
[2019-04-26 17:32:24 +0000] [INFO]: Starting slave on 10Gdell124
[2019-04-26 17:32:24 +0000] [INFO]: Starting slave on 10Gdell125
[2019-04-26 17:32:24 +0000] [INFO]: Starting slave on 10Gdell126
[2019-04-26 17:32:24 +0000] [INFO]: Starting slave on 10Gdell127
[2019-04-26 17:32:24 +0000] [INFO]: Done starting slaves
[2019-04-26 17:32:26 +0000] [INFO]: Starting Heron API Server on 10Gdell125
[2019-04-26 17:32:26 +0000] [INFO]: Waiting for apiserver to come up... 0
[2019-04-26 17:32:27 +0000] [INFO]: Waiting for apiserver to come up... 1
[2019-04-26 17:32:28 +0000] [INFO]: Waiting for apiserver to come up... 2
[2019-04-26 17:32:29 +0000] [INFO]: Waiting for apiserver to come up... 3
[2019-04-26 17:32:30 +0000] [INFO]: Waiting for apiserver to come up... 4
[2019-04-26 17:32:31 +0000] [INFO]: Waiting for apiserver to come up... 5
[2019-04-26 17:32:32 +0000] [INFO]: Waiting for apiserver to come up... 6
[2019-04-26 17:32:33 +0000] [INFO]: Waiting for apiserver to come up... 7
[2019-04-26 17:32:34 +0000] [INFO]: Waiting for apiserver to come up... 8
[2019-04-26 17:32:35 +0000] [INFO]: Waiting for apiserver to come up... 9
[2019-04-26 17:32:36 +0000] [INFO]: Waiting for apiserver to come up... 10
[2019-04-26 17:32:37 +0000] [INFO]: Done starting Heron API Server
[2019-04-26 17:32:37 +0000] [INFO]: Starting Heron Tools on 10Gdell125
[2019-04-26 17:32:37 +0000] [INFO]: Waiting for heron-tools to come up... 0
[2019-04-26 17:32:38 +0000] [INFO]: Done starting Heron Tools
[2019-04-26 17:32:38 +0000] [INFO]: Heron standalone cluster complete!
```

And I have set the `server_url` using the following command

```
heron config standalone set service_url http://10Gdell125:9000
```

But I cannot submit topology to the cluster

```
[2019-04-26 17:35:08 +0000] [ERROR]: HTTPConnectionPool(host='10gdell125', port=9000): Max retries exceeded with url: /api/v1/topologies (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x2249e10>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2019-04-26 17:35:08 +0000] [ERROR]: Failed to launch topology 'twitterSkew'
```

**Comment by Vxider** [comment]
Although the log shows that `Done starting Heron API Server`, but I found that the 9000 port is not occupied, and I cannot access `http://url:9000` in my browser.

Here is the exception when I type `heron-apiserver --base-template standalone --cluster test`.

```
Exception in thread "main" while parsing a block mapping
 in 'reader', line 2, column 1:
    heron.class.state.manager: com.t ...
    ^
expected <block end>, but found FlowEntry
 in 'reader', line 5, column 53:
     ... ction.string:  "20.0.1.124:2181","20.0.1.125:2181","20.0.1.126:2 ...
                                         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:381)
	at com.twitter.heron.common.config.ConfigReader.loadFile(ConfigReader.java:78)
	at com.twitter.heron.spi.common.ConfigLoader.loadConfig(ConfigLoader.java:37)
	at com.twitter.heron.spi.common.ConfigLoader.loadConfig(ConfigLoader.java:63)
	at com.twitter.heron.apiserver.utils.ConfigUtils.getBaseConfiguration(ConfigUtils.java:65)
	at com.twitter.heron.apiserver.Runtime.main(Runtime.java:263)
```

my `inventory.yaml` file is looks like this:

```
cluster:
- 20.0.1.124
- 20.0.1.125
- 20.0.1.126
- 20.0.1.127
zookeepers:
- 20.0.1.124
- 20.0.1.125
- 20.0.1.126
- 20.0.1.127
```

**Comment by Vxider** [comment]
Problem solved when I fold the `zookeepers:` filed in `inventory.yaml` and add ports.

[Multi-node standalone cluster](https://apache.github.io/incubator-heron/docs/operators/deployment/schedulers/standalone/#Configuration) should give a multi-node configuration example.

Now my `inventory.yaml` looks like this:

```
cluster:
- 20.0.1.124
- 20.0.1.125
- 20.0.1.126
- 20.0.1.127
zookeepers:
- 20.0.1.124:2181,20.0.1.125:2181,20.0.1.126:2181,20.0.1.127:2181
```

**Comment by joshfischer1108** [comment]
Closing since it seems to be resolved.
