### ISSUE TITLE
'No such file or directory" exception in standalone mode

### ISSUE THREAD

**Issue by Vxider** [apache/incubator-heron#3249]
I have encountered a "No such file or directory" exception when submit job to a standalone mode cluster.

Here is the log:

```
+ CORE_RELEASE_FILE=heron-core.tar.gz
+ CORE_RELEASE_DIR=heron-core
+ TOPOLOGY_PACKAGE_FILE=topology.tar.gz
+ '[' -d /home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2 ']'
+ mkdir -p /home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2
+ cd /home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2
+ '[' false == true ']'
+ ln -s /home/libing/.heron/dist/heron-core heron-core
+ ./heron-core/bin/heron-downloader -u http://dell124:9000/api/v1/file/download/22497968-1ef0-4d80-a33d-bb4a115824e0-topology.tar.gz -f . -m local -p /home/libing/.heron/conf/standalone -d ./heron-core
Apr 27, 2019 10:22:49 PM org.apache.heron.common.config.ConfigReader loadFile
WARNING: Config file name cannot be null
Apr 27, 2019 10:22:49 PM org.apache.heron.common.config.ConfigReader loadFile
WARNING: Config file name cannot be null
+ echo 31441
+ trap 'kill -TERM $PID' TERM INT
+ PID=58578
+ wait 58578
+ ./heron-core/bin/heron-executor --topology-name=WindowedWordCount1 --topology-id=WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17 --topology-defn-file=WindowedWordCount1.defn --state-manager-connection=10Gdell124:2181 --state-manager-root=/heron --state-manager-config-file=./heron-conf/statemgr.yaml --tmaster-binary=./heron-core/bin/heron-tmaster --stmgr-binary=./heron-core/bin/heron-stmgr '--metrics-manager-classpath=./heron-core/lib/metricsmgr/*' '--instance-jvm-opts=""' --classpath=heron-streamlet-examples.jar --heron-internals-config-file=./heron-conf/heron_internals.yaml --override-config-file=./heron-conf/override.yaml --component-ram-map=random-sentences-source:1073741824,flatten-into-individual-words:1073741824,reduce-operation:1073741824,consumer1:1073741824 '--component-jvm-opts=""' --pkg-type=jar --topology-binary-file=heron-streamlet-examples.jar '--heron-java-home=${JAVA_HOME}' --heron-shell-binary=./heron-core/bin/heron-shell --cluster=standalone --role=libing --environment=default '--instance-classpath=./heron-core/lib/instance/*' --metrics-sinks-config-file=./heron-conf/metrics_sinks.yaml '--scheduler-classpath=./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*' --python-instance-binary=./heron-core/bin/heron-python-instance --cpp-instance-binary=./heron-core/bin/heron-cpp-instance '--metricscache-manager-classpath=./heron-core/lib/metricscachemgr/*' --metricscache-manager-mode=disabled --is-stateful=false '--checkpoint-manager-classpath=./heron-core/lib/ckptmgr/*:./heron-core/lib/statefulstorage/*:' --stateful-config-file=./heron-conf/stateful.yaml --checkpoint-manager-ram=1073741824 --health-manager-mode=disabled '--health-manager-classpath=./heron-core/lib/healthmgr/*' --shard=2 --master-port=27612 --tmaster-controller-port=29783 --tmaster-stats-port=24500 --shell-port=29010 --metrics-manager-port=20786 --scheduler-port=23938 --metricscache-manager-master-port=24923 --metricscache-manager-stats-port=28316 --checkpoint-manager-port=24884
Traceback (most recent call last):
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/.bootstrap/_pex/pex.py", line 365, in execute
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/.bootstrap/_pex/pex.py", line 471, in execute_module
  File "/usr/lib64/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1173, in <module>
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1170, in main
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1151, in start
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1098, in start_state_manager_watches
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/statemgrs/src/python/zkstatemanager.py", line 250, in get_packing_plan
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/statemgrs/src/python/zkstatemanager.py", line 266, in _get_packing_plan_with_watch
  File "/home/libing/.pex/install/kazoo-1.3.1-py2-none-any.whl.00629d32ec52e32a542cc5a5c9ea17a8cc4c0659/kazoo-1.3.1-py2-none-any.whl/kazoo/recipe/watchers.py", line 123, in __call__
    self._get_data()
  File "/home/libing/.pex/install/kazoo-1.3.1-py2-none-any.whl.00629d32ec52e32a542cc5a5c9ea17a8cc4c0659/kazoo-1.3.1-py2-none-any.whl/kazoo/recipe/watchers.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home/libing/.pex/install/kazoo-1.3.1-py2-none-any.whl.00629d32ec52e32a542cc5a5c9ea17a8cc4c0659/kazoo-1.3.1-py2-none-any.whl/kazoo/recipe/watchers.py", line 176, in _get_data
    self._log_func_exception(data, stat, event)
  File "/home/libing/.pex/install/kazoo-1.3.1-py2-none-any.whl.00629d32ec52e32a542cc5a5c9ea17a8cc4c0659/kazoo-1.3.1-py2-none-any.whl/kazoo/recipe/watchers.py", line 135, in _log_func_exception
    result = self._func(data, stat)
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/statemgrs/src/python/zkstatemanager.py", line 272, in watch_packing_plan
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1089, in on_packing_plan_watch
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1041, in launch
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 1000, in get_commands_to_run
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 784, in _get_streaming_processes
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 572, in _get_java_instance_cmd
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 597, in _get_jvm_instance_options
  File "/home/libing/.herondata/topologies/standalone/libing/WindowedWordCount159f5c1a5-277f-4aa3-8570-56ff55e65f17/container-2/heron-core/bin/heron-executor/heron/executor/src/python/heron_executor.py", line 670, in _get_jvm_version
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I have checked the "./heron-conf/" folder has all config files

**Comment by Vxider** [comment]
Problem solved by changing my hostname lowercase.
