### ISSUE TITLE
compile error about protobuf

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3463]
I have install protobuf using "brew install protobuf , pip install protobuf", but error below is be seen yet.

ERROR: /Users/gg/heron/incubator-heron/heron/tools/tracker/tests/python/BUILD:59:1: PexPython heron/tools/tracker/tests/python/tracker_unittest_runner.pex failed (Exit 1)
Could not satisfy all requirements for protobuf==3.6.1:
    protobuf==3.6.1

**Comment by dttlgotv** [comment]
ERROR: /Users/gg/heron/incubator-heron/heron/statemgrs/tests/python/BUILD:3:1: PexPython heron/statemgrs/tests/python/configloader_unittest_runner.pex failed (Exit 1)
Could not satisfy all requirements for protobuf==3.6.1:
    protobuf==3.6.1
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
  File "/private/var/tmp/_bazel_gg/272388fad3c2810d9ff9b28da122efba/execroot/org_apache_heron/.pex/install/pex-1.2.15-py2.py3-none-any.whl.c57747ed87261721509db19020b7431dec741af3/pex-1.2.15-py2.py3-none-any.whl/pex/crawler.py", line 144, in execute
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.py", line 174, in get
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
INFO: Elapsed time: 2.664s, Critical Path: 2.34s
INFO: 4 processes: 2 local, 2 worker.
FAILED: Build did NOT complete successfully

**Comment by dttlgotv** [comment]
well on newest code
