### ISSUE TITLE
Not able to compile on Darwin platform

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3582]
**Describe the bug**
I can not run `bazel build --config=darwin_nostyle heron/...` without errors.

**To Reproduce**
1. `/.bazel_configure.py`
```zsh
❯ ./bazel_configure.py
Platform Darwin
Using C compiler          :	/usr/bin/gcc (4.2.1)
Using C++ compiler        :	/usr/bin/g++ (4.2.1)
Using C preprocessor      :	/usr/bin/cpp (11.0.0)
Using C++ preprocessor    :	/usr/bin/cpp (11.0.0)
Using linker              :	/usr/bin/ld
Using JDK                 :	/System/Library/Frameworks/JavaVM.framework/Versions/A
Using Automake            :	/usr/local/Cellar/automake/1.16.2/bin/automake (1.16.2)
Using Autoconf            :	/usr/local/Cellar/autoconf/2.69/bin/autoconf (2.69)
Using Make                :	/usr/bin/make (3.81)
Using Python3             :	/usr/bin/python3 (3.7.3)
Using Libtool             :	/usr/local/Cellar/libtool/2.4.6_2/bin/glibtool (2.4.6)
Using archiver            :	/usr/bin/ar
Using coverage tool       :	/usr/bin/gcov
Using ant                 :	/usr/local/Cellar/ant/1.10.8_1/bin/ant
dwp                       :	not found, but ok
Using nm                  :	/usr/bin/nm
objcopy                   :	not found, but ok
Using objdump             :	/usr/bin/objdump
Using strip               :	/usr/bin/strip
```
2. `bazel build --config=darwin_nostyle heron/...`
```zsh
ERROR: /Users/nnezis/workspace/incubator-heron-tracker/tools/rules/pex/BUILD:54:8: Bootstrapping pex //tools/rules/pex:pex_wrapper failed (Exit 1)
/private/var/tmp/_bazel_nnezis/dcf39782d6886b57ad31493941aeb019/execroot/org_apache_heron/bazel-out/host/bin/external/virtualenv/virtualenv.runfiles/virtualenv/virtualenv.py:1039: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_nnezis/dcf39782d6886b57ad31493941aeb019/execroot/org_apache_heron/bazel-out/host/bin/external/virtualenv/virtualenv.runfiles/virtualenv/virtualenv.py", line 2328, in <module>
    main()
  File "/private/var/tmp/_bazel_nnezis/dcf39782d6886b57ad31493941aeb019/execroot/org_apache_heron/bazel-out/host/bin/external/virtualenv/virtualenv.runfiles/virtualenv/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/private/var/tmp/_bazel_nnezis/dcf39782d6886b57ad31493941aeb019/execroot/org_apache_heron/bazel-out/host/bin/external/virtualenv/virtualenv.runfiles/virtualenv/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/private/var/tmp/_bazel_nnezis/dcf39782d6886b57ad31493941aeb019/execroot/org_apache_heron/bazel-out/host/bin/external/virtualenv/virtualenv.runfiles/virtualenv/virtualenv.py", line 1317, in install_python
    shutil.copy(original_python, py_executable)
UnboundLocalError: local variable 'original_python' referenced before assignment
```

**Comment by huijunwu** [comment]
My MacOs has several PEX environments, I used the following to force PEX on py3

```
$ PY3=$(which python3)
$ echo "PEX_PYTHON_PATH=$(dirname ${PY3})" > ~/.pexrc
$ echo "PEX_PYTHON=${PY3}" >> ~/.pexrc
$ cat ~/.pexrc
PEX_PYTHON_PATH=/usr/local/bin
PEX_PYTHON=/usr/local/bin/python3
```

not sure if this helps..

**Comment by nicknezis** [comment]
I believe this issue is resolved now. It might have been resolved when I updated the OSX Command Line tools. Closing the comment.
