### ISSUE TITLE
build failed on AArch64, Fedora 33, Java 11 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [apache/incubator-heron#3679]
[jw@cn05 heron]$ bazel build --config=centos heron/...
WARNING: Output base '/home/jw/.cache/bazel/_bazel_jw/385d1a67d6fa97fd7c95da8717fcbfef' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
WARNING: /home/jw/.cache/bazel/_bazel_jw/385d1a67d6fa97fd7c95da8717fcbfef/external/remote_java_tools_linux/BUILD:671:11: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
WARNING: /home/jw/apache/heron/heron/healthmgr/tests/java/BUILD:52:13: in srcs attribute of java_library rule //heron/healthmgr/tests/java:healthmgr-tests: please do not import '//heron/healthmgr/src/java:org/apache/heron/healthmgr/HealthManager.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'java_library', the error might have been caused by the macro implementation
INFO: Analyzed 610 targets (599 packages loaded, 6272 targets configured).
INFO: Found 610 targets...
ERROR: /home/jw/.cache/bazel/_bazel_jw/385d1a67d6fa97fd7c95da8717fcbfef/external/org_apache_zookeeper/BUILD.bazel:7:8: Executing genrule @org_apache_zookeeper//:zookeeper-srcs failed (Exit 1)

BUILD FAILED
/tmp/zookeeper.5bPOS/build.xml:410: java.net.UnknownHostException: repo1.maven.org
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:766)
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:676)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:666)

Total time: 2 seconds
Buildfile: /tmp/zookeeper.5bPOS/build.xml

init:
    [mkdir] Created dir: /tmp/zookeeper.5bPOS/build/classes
    [mkdir] Created dir: /tmp/zookeeper.5bPOS/build/lib
    [mkdir] Created dir: /tmp/zookeeper.5bPOS/build/package/lib
    [mkdir] Created dir: /tmp/zookeeper.5bPOS/build/test/lib

ivy-download:
      [get] Getting: https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar
      [get] To: /tmp/zookeeper.5bPOS/zookeeper-server/src/main/resources/lib/ivy-2.5.0-rc1.jar
      [get] Error getting https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar to /tmp/zookeeper.5bPOS/zookeeper-server/src/main/resources/lib/ivy-2.5.0-rc1.jar
ERROR: /home/jw/apache/heron/heron/stmgr/tests/cpp/server/BUILD:5:8 Executing genrule @org_apache_zookeeper//:zookeeper-srcs failed (Exit 1)
INFO: Elapsed time: 288.730s, Critical Path: 10.56s
INFO: 123 processes: 68 internal, 55 local.
FAILED: Build did NOT complete successfully
[jw@cn05 heron]$

**Comment by nicknezis** [comment]
Seems to have failed to download a dependency during the Zookeeper build step. 

Can you verify that you can download this file? https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar

Perhaps it was a temporary timeout? Network issue with your build environment?

If you still are having this issue, I can try a local build to verify that the remote dependency didn't change on us.

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 heron]$ wget https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar
--2021-03-04 10:15:51--  https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar
Connecting to 62.244.109.33:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1396340 (1.3M) [application/java-archive]
Saving to: 'ivy-2.5.0-rc1.jar'

ivy-2.5.0-rc1.jar             100%[=================================================>]   1.33M  7.34MB/s    in 0.2s

2021-03-04 10:15:51 (7.34 MB/s) - 'ivy-2.5.0-rc1.jar' saved [1396340/1396340]

[jw@cn06 heron]$ bazel build --config=centos heron/...
WARNING: Output base '/home/jw/.cache/bazel/_bazel_jw/1b14fb08ad06f2de1ed17e13b392fb80' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
WARNING: /home/jw/.cache/bazel/_bazel_jw/1b14fb08ad06f2de1ed17e13b392fb80/external/remote_java_tools_linux/BUILD:733:11: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
WARNING: /data/jw/apache/heron/heron/healthmgr/tests/java/BUILD:52:13: in srcs attribute of java_library rule //heron/healthmgr/tests/java:healthmgr-tests: please do not import '//heron/healthmgr/src/java:org/apache/heron/healthmgr/HealthManager.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'java_library', the error might have been caused by the macro implementation
INFO: Analyzed 610 targets (599 packages loaded, 6456 targets configured).
INFO: Found 610 targets...
INFO: From Compiling com_google_protobuf/src/google/protobuf/generated_message_reflection.cc [for host]:
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc: In member function 'void google::protobuf::internal::GeneratedMessageReflection::SwapOneofField(google::protobuf::Message*, google::protobuf::Message*, const google::protobuf::OneofDescriptor*) const':
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2111:37: warning: 'temp_bool' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2111 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:481:8: note: 'temp_bool' was declared here
  481 |   bool temp_bool;
      |        ^~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2111:37: warning: 'temp_double' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2111 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:480:10: note: 'temp_double' was declared here
  480 |   double temp_double;
      |          ^~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2111:37: warning: 'temp_float' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2111 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:479:9: note: 'temp_float' was declared here
  479 |   float temp_float;
      |         ^~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2111:37: warning: 'temp_uint32' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2111 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:477:10: note: 'temp_uint32' was declared here
  477 |   uint32 temp_uint32;
      |          ^~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2111:37: warning: 'temp_int64' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2111 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:476:9: note: 'temp_int64' was declared here
  476 |   int64 temp_int64;
      |         ^~~~~~~~~~
ERROR: /home/jw/.cache/bazel/_bazel_jw/1b14fb08ad06f2de1ed17e13b392fb80/external/org_apache_zookeeper/BUILD.bazel:7:8: Executing genrule @org_apache_zookeeper//:zookeeper-srcs failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

BUILD FAILED
/tmp/zookeeper.3MUXo/build.xml:410: java.net.UnknownHostException: repo1.maven.org
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:766)
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:676)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:666)

Total time: 11 seconds
Buildfile: /tmp/zookeeper.3MUXo/build.xml

init:
    [mkdir] Created dir: /tmp/zookeeper.3MUXo/build/classes
    [mkdir] Created dir: /tmp/zookeeper.3MUXo/build/lib
    [mkdir] Created dir: /tmp/zookeeper.3MUXo/build/package/lib
    [mkdir] Created dir: /tmp/zookeeper.3MUXo/build/test/lib

ivy-download:
      [get] Getting: https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar
      [get] To: /tmp/zookeeper.3MUXo/zookeeper-server/src/main/resources/lib/ivy-2.5.0-rc1.jar
      [get] Error getting https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0-rc1/ivy-2.5.0-rc1.jar to /tmp/zookeeper.3MUXo/zookeeper-server/src/main/resources/lib/ivy-2.5.0-rc1.jar
ERROR: /home/jw/.cache/bazel/_bazel_jw/1b14fb08ad06f2de1ed17e13b392fb80/external/org_apache_zookeeper/BUILD.bazel:75:11 Executing genrule @org_apache_zookeeper//:zookeeper-srcs failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
INFO: Elapsed time: 73.283s, Critical Path: 50.43s
INFO: 282 processes: 50 internal, 232 local.
FAILED: Build did NOT complete successfully
[jw@cn06 heron]$

**Comment by nicknezis** [comment]
Ok thank you. But I notice that you are not downloading directly from `repo1.maven.org`. So you're `wget` command may be working, but I assume it's because you have something else configured beyond what is shown in the text. Perhaps you are setting `HTTP_PROXY` type environment variables? How is your `wget` resolving to `62.244.109.33:8080`? I suspect the issue is that the build script that is failing is still not able to resolve the `repo1.maven.org` host. So we need to figure out how best to configure that part of the build process.

To give some extra context, this is not a build script we directly control. When the Zookeeper source package is downloaded, this is a dependency download step that is executed during the Zookeeper build. I can look into what tool is being used to download the `ivy-2.5.0-rc1.jar` and how we can configure it to use the proxy.

**Comment by nicknezis** [comment]
Here are some suggestions for how to configure Ant to use your proxy. 

https://ant.apache.org/manual/proxy.html

Maybe `ANT_ARGS` can be used to use `autoproxy` if your proxy is configured at the system level?

**Comment by LutzWeischerFujitsu** [comment]
Both options did not help.
