### ISSUE TITLE
Not able to run Python Heron tools on OSX

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3686]
**Describe the bug**
I compiled the `heron-install.sh` package. Ran it to install Heron locally. But get the following errors when I run `heron-tracker` and `heron-ui`.

```
❯ ~/.heron/bin/heron-tracker
Failed to execute PEX file. Needed macosx_11_2_x86_64-cp-38-cp38 compatible dependencies for:
 1: pyyaml
    But this pex only contains:
      PyYAML-3.13-cp38-cp38-macosx_11_x86_64.whl
 2: tornado
    But this pex only contains:
      tornado-4.0.2-cp38-cp38-macosx_11_x86_64.whl
 3: zope.interface
    But this pex only contains:
      zope.interface-4.0.5-cp38-cp38-macosx_11_x86_64.whl
```
```
❯ ~/.heron/bin/heron-ui
Traceback (most recent call last):
  File ".bootstrap/pex/environment.py", line 268, in _resolve
  File ".bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/__init__.py", line 818, in resolve
pex.vendor._vendored.setuptools.pkg_resources.DistributionNotFound: The 'MarkupSafe>=0.23' distribution was not found and is required by jinja2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 394, in execute
  File ".bootstrap/pex/pex.py", line 92, in _activate
  File ".bootstrap/pex/environment.py", line 239, in activate
  File ".bootstrap/pex/environment.py", line 408, in _activate
  File ".bootstrap/pex/environment.py", line 273, in _resolve
  File ".bootstrap/pex/orderedset.py", line 40, in update
  File ".bootstrap/pex/orderedset.py", line 33, in add
TypeError: unhashable type: 'list'
```
My version of Python (although I do have Python 2 also installed)
```
❯ python3 --version
Python 3.8.8
```

**To Reproduce**
1. `bazel build --config=darwin_nostyle scripts/packages:binpkgs`
2. `heron-install.sh --user`
3. `~/.heron/bin/heron-tracker`

**Operating System**
 - OS: Mac OSX

**Comment by thinker0** [comment]
```bash
PEX_VERBOSE=9 heron version
..........
pex: Failed to resolve a requirement: The 'pyyaml' distribution was not found and is required by the application
pex: Failed to resolve a requirement: The 'netifaces' distribution was not found and is required by the application
pex: Activating PEX virtual environment from /Users/thinker0/bin/heron :: Resolving six from [Requirement.parse('six==1.16.0; python_version != "3.0.*" and python_version != "3.1.*"pex: Unresolved requirements:
pex:   - pyyaml
pex:   - netifaces
pex: Distributions contained within this pex:
pex:   - PyYAML-3.13-cp38-cp38-macosx_10_15_x86_64.whl
pex:   - colorlog-2.6.1-py2.py3-none-any.whl
pex:   - netifaces-0.10.6-cp38-cp38-macosx_10_15_x86_64.whl
pex:   - protobuf-3.8.0-py2.py3-none-any.whl
pex:   - requests-2.12.3-py2.py3-none-any.whl
pex:   - setuptools-46.1.3-py3-none-any.whl
pex:   - six-1.16.0-py2.py3-none-any.whl
Failed to execute PEX file. Needed macosx_11_3_x86_64-cp-37-cp37m compatible dependencies for:
 1: pyyaml
    But this pex only contains:
      PyYAML-3.13-cp38-cp38-macosx_10_15_x86_64.whl
 2: netifaces
    But this pex only contains:
      netifaces-0.10.6-cp38-cp38-macosx_10_15_x86_64.whl
```

**Comment by thinker0** [comment]
https://github.com/pantsbuild/pex/releases/tag/v2.1.23

**Comment by thinker0** [comment]
Installing the vanilla version of Python solves it.
- https://www.python.org/ftp/python/3.8.10/python-3.8.10-macos11.pkg
