### ISSUE TITLE
Heron Executor error in topology pod

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3780]
**Describe the bug**
Installed Heron using Helm chart. I then submitted the `acking` example topology and round the below error output in the `heron-executor.stdout` log file. The image was of Ubuntu 20.04 OS flavor.

```
[2022-02-27 23:54:52 +0000] [INFO]: Logging pid 311 to file heron-shell-1.pid
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout: Traceback (most recent call last):
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/.bootstrap/pex/pex.py", line 476, in execute
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/.bootstrap/pex/pex.py", line 401, in _wrap_coverage
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     return runner(*args)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/.bootstrap/pex/pex.py", line 432, in _wrap_profiling
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     return runner(*args)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/.bootstrap/pex/pex.py", line 532, in _execute
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     return self.execute_entry(self._pex_info.entry_point)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/.bootstrap/pex/pex.py", line 679, in execute_entry
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     return self.execute_module(entry_point, alter_sys)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/.bootstrap/pex/pex.py", line 691, in execute_module
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     runpy.run_module(module_name, run_name="__main__", alter_sys=alter_sys)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/usr/lib/python3.8/runpy.py", line 207, in run_module
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     return _run_module_code(code, init_globals, run_name, mod_spec)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     _run_code(code, mod_globals, init_globals,
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     exec(code, run_globals)
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/heron/shell/src/python/main.py", line 30, in <module>
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     from heron.shell.src.python import handlers
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/heron/shell/src/python/handlers/__init__.py", line 18, in <module>
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     from .browsehandler import BrowseHandler
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/heron/shell/src/python/handlers/browsehandler.py", line 30, in <module>
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     class BrowseHandler(tornado.web.RequestHandler):
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:   File "/heron/.pex/unzipped_pexes/9299c4c17b2769d01784b0ce967cedbb0b94bd4e/heron/shell/src/python/handlers/browsehandler.py", line 36, in BrowseHandler
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout:     @tornado.web.asynchronous
[2022-02-27 23:54:52 +0000] [INFO]: heron-shell-1 stdout: AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

**Comment by nicknezis** [comment]
Might be related to this. https://stackoverflow.com/questions/55475879/tornado-v6-seems-to-have-dropped-tornado-web-asynchronous-coroutine-any-differe

**Comment by Code0x58** [comment]
I think the shell (and a test or two) are the last places tornado is used.
If I recall it wouldn't be particularly hairy to migrate the shell to use
fastapi like the other services, only a couple of endpoints had templates
to convert to use jinja2
